import { CompanyScoreDetail } from 'src/app/core/models/company-score-detail.model';

export const MockScoreDetails = [
  // {
  //   companyCode: 'as0001',
  //   columnCode: 'CURRENT_DEBT_TO_INCOME',
  //   score: 2.01,
  //   max: 3,
  // },
  {
    companyCode: 'as0001',
    columnCode: 'CUSTOMERS_CONDITION_LATEST_180',
    score: 2.19,
    max: 3,
  },
  {
    companyCode: 'as0001',
    columnCode: 'CUSTOMERS_CONDITION_LATEST_30',
    score: 2.1,
    max: 3,
  },
  {
    companyCode: 'as0001',
    columnCode: 'CUSTOMERS_CONDITION_LATEST_365',
    score: 2.85,
    max: 3,
  },
  {
    companyCode: 'as0001',
    columnCode: 'CUSTOMERS_CONDITION_LATEST_7',
    score: 2.73,
    max: 3,
  },
  {
    companyCode: 'as0001',
    columnCode: 'CUSTOMERS_CONDITION_LATEST_90',
    score: 1.95,
    max: 3,
  },
  {
    companyCode: 'as0001',
    columnCode: 'CUSTOMERS_GROWTH_FROM_180',
    score: 2.07,
    max: 3,
  },
  {
    companyCode: 'as0001',
    columnCode: 'CUSTOMERS_GROWTH_FROM_270',
    score: 2.91,
    max: 3,
  },
  {
    companyCode: 'as0001',
    columnCode: 'CUSTOMERS_GROWTH_FROM_30',
    score: 3,
    max: 3,
  },
  {
    companyCode: 'as0001',
    columnCode: 'CUSTOMERS_GROWTH_FROM_365',
    score: 2.76,
    max: 3,
  },
  {
    companyCode: 'as0001',
    columnCode: 'CUSTOMERS_GROWTH_FROM_90',
    score: 2.79,
    max: 3,
  },
  {
    companyCode: 'as0001',
    columnCode: 'CUSTOMERS_KEEP_GOOD_CONDITION',
    score: 1.86,
    max: 3,
  },
  {
    companyCode: 'as0001',
    columnCode: 'CUSTOMERS_STABILITY',
    score: 2.61,
    max: 3,
  },
  {
    companyCode: 'as0001',
    columnCode: 'CUSTOMERS_SUDDEN_FALL_PAST',
    score: 2.58,
    max: 3,
  },
  {
    companyCode: 'as0001',
    columnCode: 'CUSTOMERS_SUDDEN_FALL_RECENTLY',
    score: 2.97,
    max: 3,
  },
  { companyCode: 'as0001', columnCode: 'CUSTOMERS_TREND', score: 2.58, max: 3 },
  {
    companyCode: 'as0001',
    columnCode: 'ESTABLISHED_YEARS',
    score: 2.07,
    max: 3,
  },
  {
    companyCode: 'as0001',
    columnCode: 'FOOD_DRINK_COST_RATE',
    score: 2.61,
    max: 3,
  },
  {
    companyCode: 'as0001',
    columnCode: 'FOOD_LABOR_COST_RATE',
    score: 2.13,
    max: 3,
  },
  {
    companyCode: 'as0001',
    columnCode: 'LOAN_TO_MONTHLY_SALES',
    score: 1.65,
    max: 3,
  },
  {
    companyCode: 'as0001',
    columnCode: 'PERSONAL_COST_RATE',
    score: 2.64,
    max: 3,
  },
  {
    companyCode: 'as0001',
    columnCode: 'PRICE_PER_CUSTOMER_GROWTH_FROM_365',
    score: 2.64,
    max: 3,
  },
  {
    companyCode: 'as0001',
    columnCode: 'PURCHASE_COST_RATE',
    score: 1.95,
    max: 3,
  },
  {
    companyCode: 'as0001',
    columnCode: 'PURCHASE_COST_RATE_OF_SUPERIORS',
    score: 2.73,
    max: 3,
  },
  {
    companyCode: 'as0001',
    columnCode: 'SALES_CONDITION_LATEST_180',
    score: 2.13,
    max: 3,
  },
  {
    companyCode: 'as0001',
    columnCode: 'SALES_CONDITION_LATEST_30',
    score: 1.83,
    max: 3,
  },
  {
    companyCode: 'as0001',
    columnCode: 'SALES_CONDITION_LATEST_365',
    score: 2.52,
    max: 3,
  },
  {
    companyCode: 'as0001',
    columnCode: 'SALES_CONDITION_LATEST_7',
    score: 1.8,
    max: 3,
  },
  {
    companyCode: 'as0001',
    columnCode: 'SALES_CONDITION_LATEST_90',
    score: 2.25,
    max: 3,
  },
  {
    companyCode: 'as0001',
    columnCode: 'SALES_GROWTH_FROM_180',
    score: 2.07,
    max: 3,
  },
  {
    companyCode: 'as0001',
    columnCode: 'SALES_GROWTH_FROM_270',
    score: 2.34,
    max: 3,
  },
  {
    companyCode: 'as0001',
    columnCode: 'SALES_GROWTH_FROM_30',
    score: 2.94,
    max: 3,
  },
  {
    companyCode: 'as0001',
    columnCode: 'SALES_GROWTH_FROM_365',
    score: 1.56,
    max: 3,
  },
  {
    companyCode: 'as0001',
    columnCode: 'SALES_GROWTH_FROM_90',
    score: 2.55,
    max: 3,
  },
  {
    companyCode: 'as0001',
    columnCode: 'SALES_KEEP_GOOD_CONDITION',
    score: 1.74,
    max: 3,
  },
  { companyCode: 'as0001', columnCode: 'SALES_STABILITY', score: 2.58, max: 3 },
  {
    companyCode: 'as0001',
    columnCode: 'SALES_SUDDEN_FALL_PAST',
    score: 1.71,
    max: 3,
  },
  {
    companyCode: 'as0001',
    columnCode: 'SALES_SUDDEN_FALL_RECENTLY',
    score: 2.1,
    max: 3,
  },
  { companyCode: 'as0001', columnCode: 'SALES_TREND', score: 2.7, max: 3 },
  {
    companyCode: 'as0001',
    columnCode: 'STOCK_LISTING_CATEGORY',
    score: 2.1,
    max: 3,
  },
] as CompanyScoreDetail[];
